#!name=Personal
#!desc=自用规则
[rules]

DOMAIN-KEYWORD,redd,PROXY
DOMAIN-SUFFIX,line-apps.com,PROXY
DOMAIN-SUFFIX,line.me,PROXY
DOMAIN-SUFFIX,line.naver.jp,PROXY
DOMAIN-SUFFIX,cloudfront.net,PROXY
DOMAIN-SUFFIX,tunein.com,PROXY
DOMAIN-SUFFIX,radiotime.com,PROXY
DOMAIN-SUFFIX,github.com,PROXY
DOMAIN-SUFFIX,githubusercontent.com,PROXY

#musi
DOMAIN-SUFFIX,supersonicads.com,REJECT
DOMAIN-SUFFIX,app-analytics-services.com,REJECT
DOMAIN-SUFFIX,iads.unity3d.com,REJECT
DOMAIN-SUFFIX,appsflyer.com,REJECT
DOMAIN-SUFFIX,mtgglobals.com,REJECT
DOMAIN-SUFFIX,inner-active.mobi,REJECT
DOMAIN-SUFFIX,inhousedsp.com,REJECT
DOMAIN-SUFFIX,rubiconproject.com,REJECT
DOMAIN-SUFFIX,ybp.yahoo.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
DOMAIN-SUFFIX,appier.net,REJECT
DOMAIN-SUFFIX,amazon-adsystem.com,REJECT
